### PR TITLE
Respect endpoint name

### PR DESCRIPTION
**Pull request by caseydavenport**

### CODE REVIEW

**Comment by robbrockbank** [comment]
Looks like you might need to update the **eq** method too.

Seems odd that we haven't hit issues with this before - I guess we don't read and write to the same endpoint usually?

**Comment by caseydavenport** [comment]
I think it was fine before because every component was generating the endpoint ID in the same way.

Once the endpoint ID is something different it all falls apart.

**Comment by caseydavenport** [comment]
@robbrockbank `__eq__` has been updated.

**Comment by robbrockbank** [comment]
LGTM

**Pull request merged**
