### PR TITLE
Update frozen requirements.

### PR DESCRIPTION
**Pull request by ozdanborne**
Notably this uses nonforked python-etcd.

Generated just by running `make update-frozen`

### CODE REVIEW

**Comment by tomdee** [comment]
Erm... quite a lot going on here. Have you thought about all these changes and you'll vouch for them all?

**Comment by ozdanborne** [comment]
@tomdee I misunderstood the purpose of having requirements and frozen-requirements. Updated to just update etcd in this PR.

I don't actually see the purpose of having requirements.txt anymore. Doesn't seem like anything uses or builds from it.

**Comment by caseydavenport** [comment]
@djosborne I'm assuming you've verified v0.4.2 includes the commit that was pinned before?

**Comment by ozdanborne** [comment]
I assumed since 0.4.2 was released a month after the necessary commits, it would.

But shouldn't have assumed. The necessary commits weren't included.

**Pull request closed without merging**
